### ISSUE TITLE
This project is no longer working

### ISSUE THREAD

**Issue by gerrotaste** [oholiab/brute-seco#3]
Hi, I was trying to test this project out but seems like something changed. 

I made a wallet with new password then launched the script and it seems like it can't recognize valid password so it just goes through them and do nothing. 

Valid password on this screenshot is I81SA1237!@^adshF!ZcASD
![image](https://user-images.githubusercontent.com/86052115/122378996-5c755180-cf5e-11eb-8613-327e49d1d12f.png)

**Comment by oholiab** [comment]
It's entirely possible that the wallet has changed how it does things since I wrote this 3 years ago. I'll leave the issue open in case anyone else wants to do further debugging but I'm not going to be spending time on this.

**Comment by gerrotaste** [comment]
Hey. Sorry, couldn't find any way to contact you in private. Would you be interested in fixing this script for $2000 in BTC/ETH/XMR ?
